kind = "web"
previewPath = "/"
title = "АС СКЛ v2.0"
version = "1.0.0"

[[services]]
localPort = 5000
name = "АС СКЛ"
paths = ["/", "/api/v1"]

[services.development]
run = "python artifacts/as-skl/run.py"
